### ISSUE TITLE
Optional data support

### ISSUE THREAD

**Issue by fracek** [kochavalabs/xdr-rs-serialize#19]
## Describe the feature 

The standard supports [optional types](https://tools.ietf.org/html/rfc4506#page-14), I think this can be added by adding an implementation of the relevant traits for `Option<T>`.

I can work on a PR for this.

**Comment by kbartush** [comment]
Generally I've been using unions with the 0 case as void for optional items. I believe they create the same XDR output as an optional item. Adding an actual Option<T> would be much cleaner though.

**Comment by kbartush** [comment]
Had a hiccup in the deployment, rather than manually fixing anything, I just cut a new release at v0.2.3 that has your changes. If there are any issues let me know.
